# Generated by Django 4.2.6 on 2023-11-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0004_rename_areas_area_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
