# Generated by Django 4.2.6 on 2023-11-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0005_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villabetel.area', verbose_name='Zona')),
            ],
        ),
    ]
