# Generated by Django 4.2.6 on 2023-11-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0009_alter_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='waiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='villabetel.waiter'),
            preserve_default=False,
        ),
    ]
