# Generated by Django 4.2.6 on 2023-11-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0011_remove_account_product_account_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villabetel.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villabetel.product')),
            ],
        ),
    ]
