# Generated by Django 4.2.6 on 2023-11-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0012_productquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='products',
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
