# Generated by Django 4.2.6 on 2023-11-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0014_account_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ammount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
