# Generated by Django 4.2.6 on 2023-11-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0015_alter_account_ammount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='products',
        ),
    ]
