# Generated by Django 4.2.6 on 2023-11-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0016_remove_account_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantities', to='villabetel.account'),
        ),
    ]
