# Generated by Django 4.2.6 on 2023-11-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villabetel', '0017_alter_productquantity_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
